[package]
name = "alertrs"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.40.0", features = ["full"] }
tokio-stream = "0.1.17"
tokio-tungstenite = "0.26.2"
futures = "0.3"
warp = "0.3"
